import "~/styles/globals.css";

import { type Metadata } from "next";

import { BaselineProvider } from "~/state/BaselineContextProvider";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [
    { rel: "icon", url: "/favicon.ico" },
    {
      rel: "apple-touch-icon",
      url: "/apple-touch-icon.png",
    },
  ],
};

export default function Layout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return <BaselineProvider>{children}</BaselineProvider>;
}
